#### Spam And Ham Project Using BOW + TFidf and Multinomial Naive Bayes Algorithm

##### Best Practises For Solving ML Problems
1. Data Cleaning and Preprocessing
2. Train and Test split
3. BOW / TF-IDF (Sentence --------> Vector) {Preventing Data Leakage}
4. Training ML Model

In [1]:
import pandas as pd
df = pd.read_csv("spam.csv",encoding="latin1")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [2]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [3]:
# Rename 'v1' to 'label' and 'v2' to 'Message'
df.rename(columns={'v1': 'label', 'v2': 'Message'}, inplace=True)

# Drop the unwanted columns
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

# Display the updated DataFrame
print(df.head())

  label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [4]:
df.head()

label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   Message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


### Data Cleaning and Preprocessing

In [6]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lz = WordNetLemmatizer()
from nltk.stem import SnowballStemmer
sb = SnowballStemmer('english')
from nltk.stem import PorterStemmer
pt = PorterStemmer()

In [7]:
corpus = []
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]',' ',df['Message'][i])
    review = review.lower()
    review =review.split()
    review = [lz.lemmatize(word)for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [9]:
### Output Feature
y = pd.get_dummies(df['label'])
y = y.iloc[:,0].values

In [10]:
y.shape

(5572,)

### Train_Test_split

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.25, random_state=42)

### Create Bag of Words model

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500 , ngram_range = (2,2))

In [13]:
len(X_train),len(y_train)

(4179, 4179)

In [14]:
X_train

['u call',
 'tell u headache want use hour sick time',
 'never try alone take weight tear come ur heart fall ur eye always remember stupid friend share bslvyl',
 'raji pls favour pls convey birthday wish nimya pls today birthday',
 'time prob',
 'hi kate lovely see tonight ill phone tomorrow got sing guy gave card xxx',
 'usual iam fine happy amp well',
 'nope watching tv home going v bored',
 'p u ur grown right',
 'k wat tht incident',
 'u awake snow',
 'good wondering wont say hi smiling coping long distance',
 'intrepid duo great time see soon',
 'gobi art college',
 'credit topped http www bubbletext com renewal pin tgxxrz',
 'thought put back box',
 'wnt buy bmw car urgently vry urgent hv shortage lt gt lac source arng dis amt lt gt lac thats prob',
 'hi mobile lt gt added contact list www fullonsms com great place send free sm people visit fullonsms com',
 'easy ah sen got selected mean good',
 'know lacking particular dramastorm detail part worried',
 'k k business',
 'probably

In [15]:
## Independent feature
X_train = cv.fit_transform(X_train).toarray()

In [16]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
X_test = cv.transform(X_test).toarray()

In [18]:
import numpy as np
np.set_printoptions(edgeitems = 30,linewidth = 100000,formatter = dict(float = lambda x:"%.3g" %x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [19]:
cv.vocabulary_

{'sick time': 1884,
 'come ur': 253,
 'ur heart': 2333,
 'raji pls': 1658,
 'pls favour': 1574,
 'favour pls': 559,
 'pls convey': 1570,
 'convey birthday': 299,
 'birthday wish': 54,
 'wish nimya': 2447,
 'nimya pls': 1428,
 'pls today': 1579,
 'today birthday': 2179,
 'hi kate': 1001,
 'tonight ill': 2228,
 'usual iam': 2366,
 'iam fine': 1079,
 'fine happy': 575,
 'happy amp': 949,
 'amp well': 16,
 'watching tv': 2404,
 'say hi': 1778,
 'see soon': 1805,
 'http www': 1068,
 'hv shortage': 1077,
 'shortage lt': 1877,
 'lt gt': 1286,
 'gt lac': 916,
 'lac source': 1171,
 'dis amt': 388,
 'lac thats': 1172,
 'hi mobile': 1003,
 'gt added': 897,
 'added contact': 4,
 'contact list': 290,
 'fullonsms com': 674,
 'com great': 228,
 'great place': 889,
 'send free': 1822,
 'free sm': 631,
 'sm people': 1924,
 'people visit': 1519,
 'easy ah': 458,
 'sen got': 1817,
 'got selected': 863,
 'selected mean': 1812,
 'probably earlier': 1622,
 'sorry meeting': 1966,
 'meeting call': 1321,
 'cal

### Machine Learning Model Training (Multinomial Naive Bayes Algorithm)

In [20]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [21]:
y_pred = spam_detect_model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9633883704235463
[[ 144   47]
 [   4 1198]]
              precision    recall  f1-score   support

       False       0.97      0.75      0.85       191
        True       0.96      1.00      0.98      1202

    accuracy                           0.96      1393
   macro avg       0.97      0.88      0.91      1393
weighted avg       0.96      0.96      0.96      1393



### Create TFIDF model

In [23]:
### Output Feature
y = pd.get_dummies(df['label'])
y = y.iloc[:,0].values

In [24]:
y.shape

(5572,)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 100,ngram_range=(2,2))
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.25, random_state=42)
X_train = tfidf.fit_transform(X_train).toarray()

In [26]:
X_test = tfidf.transform(X_test).toarray()

In [27]:
import numpy as np
np.set_printoptions(edgeitems = 30,linewidth = 100000,formatter = dict(float = lambda x:"%.3g" %x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [28]:
tfidf.vocabulary_

{'watching tv': 99,
 'http www': 47,
 'lt gt': 57,
 'call later': 6,
 'please call': 69,
 'free entry': 31,
 'chance win': 14,
 'good morning': 35,
 'great day': 37,
 'prize claim': 73,
 'claim call': 15,
 'trying contact': 87,
 'dating service': 21,
 'last week': 51,
 'claim ur': 17,
 'po box': 71,
 'sorry call': 83,
 'free call': 30,
 'call claim': 3,
 'call landline': 5,
 'one day': 65,
 'double min': 24,
 'call mobileupd': 7,
 'mobileupd call': 59,
 'call optout': 8,
 'give call': 34,
 'wat time': 98,
 'happy birthday': 42,
 'send stop': 80,
 'urgent trying': 94,
 'draw show': 25,
 'show prize': 81,
 'prize guaranteed': 74,
 'guaranteed call': 40,
 'claim code': 16,
 'valid hr': 95,
 'pobox wq': 72,
 'new year': 62,
 'next week': 63,
 'let know': 52,
 'gt min': 39,
 'like lt': 53,
 'cant pick': 12,
 'pick phone': 68,
 'phone right': 67,
 'right pls': 76,
 'pls send': 70,
 'send message': 79,
 'take care': 85,
 'selected receive': 78,
 'get back': 33,
 'holiday cash': 46,
 'await co

### Machine Learning Model Training (Multinomial Naive Bayes Algorithm)

In [29]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train,y_train)

In [30]:
## Predict
y_pred = spam_tfidf_model.predict(X_test)

In [31]:
# Predict Result
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.923905240488155
[[  89  102]
 [   4 1198]]
              precision    recall  f1-score   support

       False       0.96      0.47      0.63       191
        True       0.92      1.00      0.96      1202

    accuracy                           0.92      1393
   macro avg       0.94      0.73      0.79      1393
weighted avg       0.93      0.92      0.91      1393

